[package]
name = "ttk4145-elevator"
version = "0.1.0"
authors = ["Øyvind <oyvindskaaden@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossbeam-channel = "0.5"
socket2 = "0.4.0"